# Site settings
title: My Portfolio
email: bv.iitb.2023@gmail.com
description: Physics - Math = Philosophy
baseurl: "/blog/"
url: "https://aravindbharathi.github.io/"

twitter_username: bvcxz1_
github_username: aravindbharathi
instagram_username: aburstofradium

# Build settings
markdown: kramdown
